apiVersion: v1
kind: Service
metadata:
    name: flask-app-service
    labels:
        app: flask-app
spec:
    type: LoadBalancer
    selector:
        app: flask-app
    ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http