name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    # -
    #   name: Build docker image and pushing it
    #   env:
    #     TAG: $(date +%s)
    #   run: | 
    #     docker build . -t edgariphdz98/docker-flask-app-portafolio:$TAG
      
    # -
    #   name: Pushing docker image to registry

     # uses: docker/build-push-action@v1
      #with:
      #repository: edgariphdz98/docker-flask-app-portafolio: ${{ github.run_number }}
      #  tags: latest , ${{ github.run_number }}
       # username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}
#     - uses: mr-smithers-excellent/docker-build-push@v5
#       name: Build & push Docker image to Registry
#       with:
#         image: edgariphdz98/docker-flask-app-portafolio
#         tags: $(date +%s), latest
#         registry: registry.hub.docker.com
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
