name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ImageDeploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Code
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: edgariphdz98/docker-flask-app-portafolio:latest
      #   edgariphdz98/docker-flask-app-portafolio:${{ secrets.VERSION }}
      # Set the target AKS cluster.
      - name: Logging int to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: Setting context with AKS
      #   uses: azure/aks-set-context@v2.0
      #   with:
      #     cluster-name: Flask-App-Kluster
      #     resource-group: app-deployment-resources
      # -
      #   name: updating version Number of Image
      #   uses: hmanzur/actions-set-secret@v2.0.0
      #   with:
      #     name: 'VERSION'
      #     value: $((${{ secrets.VERSION }}+1))
      #     repository: edgariph98/CI-CD-FlaskApp
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
