name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    -
      name: Build Docker Image and Push to docker.io registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: edgariphdz98/docker-flask-app-portafolio:latest

